### ISSUE TITLE
Add alpine-based node images

### ISSUE THREAD

**Issue by Exoticalgi** [aerokube/selenoid#100]
Consider adding alpine-based node images.

**Comment by vania-pooh** [comment]
@Exoticalgi already tried. Probably because of /bin/sh inside these images it does not work. Currently all images are using the same base layer with Ubuntu 16.04, fonts, flashplayer and so on. So you don't need to redownload all for each browser image.

**Comment by Exoticalgi** [comment]
What about this: https://github.com/yikaus/docker-alpine-bash/blob/master/Dockerfile

**Comment by vania-pooh** [comment]
@Exoticalgi I don't think that we'll economize a lot of space with Alpine in case of browser images because in addition to browser we need fonts, X server, some libs and so on. So in my opinion after installing all this stuff to Alpine you will get almost the same size. Will try during next days. Anyway rebuilding images from scratch is too much work to get this done fast.

**Comment by Exoticalgi** [comment]
@vania-pooh OK. Also check this image: https://hub.docker.com/r/blitznote/debootstrap-amd64/

**Comment by vania-pooh** [comment]
Won't fix. Did several attempts on Alpine. Does not work. Anyway we are still using Alpine for Selenoid and Selenoid UI images.
