### ISSUE TITLE
 Error: Failed to create session. for mobile chrome browser

### ISSUE THREAD

**Issue by RollerIn** [aerokube/selenoid#1176]
browsers.json
```
"chrome-mobile": {
    "default": "mobile-75.0",
    "versions": {
      "mobile-75.0": {
        "image": "selenoid/chrome-mobile:75.0",
        "port": "4444",
        "path": "/wd/hub"
      }
    }
  }
```
config.js
```
{
                //hostname: 'selenoid.mobile',
                maxInstances: 1,
                browserName: 'chrome-mobile',
                browserVersion: 'mobile-75.0',
                'selenoid:options': {
                    enableVnc: true,
                    enableLog: true,
                },
            }

```
Services in config file
```
services: [
            [
                'selenoid-standalone', {
                pathToBrowsersConfig: './browsers.json',
                customSelenoidContainerName: 'wdio-selenoid',
            },
            ],
        ],
```
package:
```
{
    "devDependencies": {
        "wdio-selenoid-standalone-service": "^1.0.0"
    }
}
```
can some one help what am missing here? am working using webdriverIO

**Comment by RollerIn** [comment]
@vania-pooh sorry, am not getting you. 
if I want to run mobile tests what setup I can do ...my os is Mac
can you please guide me?

**Comment by vania-pooh** [comment]
@RollerIn no, that's impossible. Will work only under Linux. Docker for Mac does not forward virtualization to containers.

**Comment by RollerIn** [comment]
@vania-pooh ,I am really in confusion mode, I have pulled amd64/ubantu image and used same as above config ..but still getting issue , dont mind can you suggest me what aim missing here ...
 ```
Request failed with status 400 due to invalid argument: Requested environment is not available
[0-0] 2022-02-22T11:40:49.864Z ERROR webdriver: invalid argument: Requested environment is not available
```
do I need to pass anything here additionally
```
services: [
            [
                'selenoid-standalone', {
                pathToBrowsersConfig: './browsers.json',
                customSelenoidContainerName: 'wdio-selenoid',
            },
            ],
        ],
```

**Comment by vania-pooh** [comment]
@RollerIn you are trying to request a browser that is missing in `browsers.json`.

**Comment by RollerIn** [comment]
Can anyone guide me what steps need to take care from scratch to set up for android mobile setup to run on solenoid?
Really worrying to run mobile browser on Selenoid. 
I have pulled amd64/ubantu and did above setup but still not able to achieve it.

**Comment by vania-pooh** [comment]
@RollerIn

```
  "chrome-mobile": {
    "default": "mobile-75.0",
```

Browser name should be just `chrome`. Only version can contain `mobile`. This is hard-coded in Appium.

**Comment by RollerIn** [comment]
Thank you @vania-pooh , after I have change to chrome , I can see Selenoid UI with but failed to create session
![image](https://user-images.githubusercontent.com/17290705/155447329-97bb70db-5bda-4276-98ee-fc82340eb178.png)
Error log:
```
 request failed due to response error: session not created
ERROR webdriver: Request failed with status 500 due to session not created: wait: http://172.17.0.4:4444/wd/hub does not respond in 30s
ERROR webdriver: session not created: wait: http://172.17.0.4:4444/wd/hub does not respond in 30s
```

**Comment by vania-pooh** [comment]
@RollerIn increase session startup timeout to 2 minutes with `-session-attempt-timeout 2m` flag. 30 seconds is too small for Android.

**Comment by RollerIn** [comment]
@vania-pooh even after increasing 2m,3m,5m,,no use 
even tried manually on seleniodUI to create sessions for both android and mobile chrome..but failed to create sessions
![image](https://user-images.githubusercontent.com/17290705/155577590-63e79e5f-c4cc-4e78-a9a1-9b0147ec0934.png)

log:
 `TimeoutError: Timeout awaiting 'request' for 120000ms when running "http://127.0.0.1:4444/wd/hub/session" with method "POST" and args "{"capabilities":{"alwaysMatch":{"browserName":"chrome","browserVersion":"mobile-75.0","selenoid:options":{"enableVnc":true,"enableLog":true}},"firstMatch":[{}]},"desiredCapabilities":{"browserName":"chrome","browserVersion":"mobile-75.0","selenoid:options":{"enableVnc":true,"enableLog":true}}}"
`
still am I missing anything is here

**Comment by vania-pooh** [comment]
@vania-pooh Android images only work under Linux with virtualization support enabled.

**Comment by RollerIn** [comment]
sorry asking again, if possible can you share what exactly I need to do , am new to this and not aware on "Linux with virtualization support enabled." ..can I get any reference link to understand step by step

**Comment by vania-pooh** [comment]
@RollerIn either take a Linux hardware server or a virtual machine with nested virtualization enabled. Such machines can be e.g. launched in Google Cloud (https://cloud.google.com/compute/docs/instances/nested-virtualization/enabling). In AWS I think only *.metal instances will work.

**Comment by HarikrishnanVK** [comment]
I use Linux with ubuntu where nested virtualisation is enabled and I am trying to work with mobile-chrome with WebdriverIO.

Below is the error I came across while trying to run in mobile-chrome,

" [mobile_chrome mobile-86.0 Android #0-0] An unknown server-side error occurred while processing the command. Original error: URI and package arguments are required ". 

I am using the capabilities as mentioned in selenoid ui and my mobile-chrome image is already pulled from docker and consumed by selenoid UI. Also I could see session getting created but not proceeding further with the tests. Not sure whether this is a bug or some missing configuration which is not updated in 'selenoid ui capabilities' for JavaScript.

Attached screenshots below for reference.

![image](https://github.com/aerokube/selenoid/assets/47863936/3831283a-e4a2-4627-b3bb-a9253f383143)

![image](https://github.com/aerokube/selenoid/assets/47863936/8ee284d6-a827-4647-8b13-07b8105d733b)

![image](https://github.com/aerokube/selenoid/assets/47863936/03de84df-90cb-4808-9948-3ee05eeae86c)

Note : I am not using any selenoid related service from wdio as it seems to be very slow and not working due to lack of maintenance and I am connecting to solenoid directly by mentioning the port 4444 referring to the localhost. I made my tests working with web browsers but struck with mobile-chrome which is part of requirement. 

@vania-pooh Any help would be appreciated. Thanks !!

**Comment by vania-pooh** [comment]
@HarikrishnanVK you need to pass `app` capability with APK URL.

**Comment by HarikrishnanVK** [comment]
@vania-pooh I am trying to test web app with mobile-chrome image provided by selenoid. And it's already in place. Not sure which apk url I need to pass. I am not testing any native app here with apk extension. I assume that mobile-chrome image of selenoid should have chrome configured inside the mobile and it should be able to pick the test without the help of appium service.

Can I get some working set of capabilities for running this. I guess the capabilities provided in selenoid ui isn't enough. Also Could not find one in the official documention.

**Comment by vania-pooh** [comment]
@HarikrishnanVK what Docker image are you using with Selenoid?

**Comment by HarikrishnanVK** [comment]
@vania-pooh selenoid chrome-mobile . Version 86.  https://hub.docker.com/layers/selenoid/chrome-mobile/86.0/images/sha256-e42762253bc2608e3ccfae7318481e2660a57f566b63a7c1e5e73036951ae2de?context=explore

**Comment by vania-pooh** [comment]
@HarikrishnanVK `browserName` should be always `chrome` but `browserVersion` can be any value, e.g. `mobile-86.0`.

**Comment by HarikrishnanVK** [comment]
It works. Thanks. Additionally I also changed the Json title of the browser from browsers.json as selenoid picks the name of its browser from browsers.json file.

![image](https://github.com/aerokube/selenoid/assets/47863936/cb1601a3-eaa3-4a3a-b4ac-89514139154e)

This sets the limitation of having only either web chrome or mobile chrome in the browsers.json but can not have both.

![image](https://github.com/aerokube/selenoid/assets/47863936/447d1ce0-55ce-4ec2-9287-01d1dcc68409)

Guess that's why document suggests to have the name as 'mobile-chrome' for mobile execution in browsers.json. But some how, the logic expects only the 'chrome' keyword for the execution to be triggered on chrome browser. 

Ideally we should have a unique identifier to identify the browsers of desktop/mobile environment. This could be a bug.

**Comment by vania-pooh** [comment]
@HarikrishnanVK you can put all versions under the same `chrome` key in `browsers.json`.

**Comment by HarikrishnanVK** [comment]
As an alternative, I tried to set device resolution using 'screenResolution' capability but that didn't had any effect on selenoid UI looking at the emulator. It just behaves like desktop browser.

Resolution capability used in selenoid options: 

![image](https://github.com/aerokube/selenoid/assets/47863936/5f398905-c136-4a37-acf7-612ebce09d8d)

Android emulator image in Selenoid UI which remains unchanged after passing the capability: 

![image](https://github.com/aerokube/selenoid/assets/47863936/347f9a2e-483c-4c00-9310-dae9371b2ca5)

Expected one should be like Android Studio emulator image that runs in local:

![image](https://github.com/aerokube/selenoid/assets/47863936/be3f70e5-14f2-422c-9771-7d00d6b0e988)

From the above images, you can see the difference between selenoid and android studio emulators. Test fails as selenoid is not setting the resolution according to the capability.

**Comment by vania-pooh** [comment]
@HarikrishnanVK you can rebuild image from source code to use any device and skin. https://github.com/aerokube/images/blob/master/selenium/automate_android.sh
