### ISSUE TITLE
[Question] - Can the selenoid images and client be used together with a VNC client to replace Browserstack and be able to perform manual actions?

### ISSUE THREAD

**Issue by GSasu** [aerokube/selenoid#1204]
Hello 👋 

I am doing some research into potential tools that offer easy OS setup to replace Browserstack (mainly for manual interactions).
Is it possible to use a normal VNC client and make use of VNC based images to gain access to the guest OS desktop and perform manual checks?

I know that this works wonderfully with automation, I just want to know if this is possible as from the documentation it is not very clear.

Thanks in advance!

**Comment by vania-pooh** [comment]
@GSasu browser images themselves contain regular VNC server listening on port 5900. The problem is that if you wish to e.g. run 10 containers like this in parallel, then you can't use the same port for every container. In Selenoid this is solved by proxying VNC (RFB) traffic via WebSockets using one HTTP port. In Selenoid UI we use [noVNC](https://github.com/novnc/novnc/) to connect to the web-socket and show browser screen. Not sure whether desktop native clients can do this. But if you go directly to the image port without using Selenoid, they will certainly work.

**Comment by GSasu** [comment]
@vania-pooh Thank you kindly for your reply. Great details and information shared. I will do some research and PoCs in regards to this. Are you interested in the outcome and maybe a contribution to the documentation detailing how something like this can be done if the PoCs are successful?

**Comment by vania-pooh** [comment]
@GSasu yes, feel free to post here.
