### ISSUE TITLE
In Selenoid-ui  QUEUE is not getting updated properly 

### ISSUE THREAD

**Issue by Puvvada-Ananth** [aerokube/selenoid#1285]
Hello Everyone, 
I have the following issue with Selenoid-UI, Not sure why it is causing. We have a test case execution environment with GGR and pointed to Selenoid agents with limit of 8 sessions in each agent. But suddenly i started seeing that in selenoid-ui  QUEUE is not getting updated properly with exact numbers. Please find the attachment for reference. if you see in the screenshot we still have 100 sessions available and still queue getting updated. Could some one help plz!
Thanks in advance.
![image](https://user-images.githubusercontent.com/106600556/205612069-4770d366-f80b-4ff2-8a95-05cb4a4617bb.png)

**Comment by vania-pooh** [comment]
@Puvvada-Ananth you overloaded your cluster. Queue should be zero or almost zero.

**Comment by Puvvada-Ananth** [comment]
I did not get you, As per my understanding if the available session are 100 and if we trigger 150 test cases 50 should be in queue and 100 must get occupied which is not happening.

**Comment by vania-pooh** [comment]
@Puvvada-Ananth you have total limit of 112, but used is only 12 and 8 containers are starting. Queued should be only non-zero when cluster is fully occupied, i.e. 112/112 or something near this.

**Comment by Puvvada-Ananth** [comment]
@vania-pooh yes i understood that. But, when ever a session is occupied the queue size must be reduced right that is not happening in my case.

**Comment by vania-pooh** [comment]
@Puvvada-Ananth probably because new requests are coming from your CI \ code.

**Comment by Puvvada-Ananth** [comment]
@vania-pooh No no if no job or sessions are triggered then also the queue size is non-zero which is not expected.

**Comment by vania-pooh** [comment]
@Puvvada-Ananth then need more details about your environment. What is your Selenoid release version? How many browser sessions are being run in parallel?

**Comment by maggosourabh** [comment]
@Puvvada-Ananth  Not sure about your case. But I was also facing the similar challenges when the quota was not completely up (say 112 was expected but 88 were shown due to selenoid service down on few machines) and queue was 5000+. However, once the machines were up again with full quota available, queue suddenly disappeared even though there was no execution of those 5000+ queue.

So it surely seems to have a problem with the data shown, but couldn't find the root cause for it.

@vania-pooh  - we are using selenoid with combination of windows, docker desktop, ubuntu app together with wsl2 where we use latest version of selenoid and ggr as much as possible.

**Comment by maggosourabh** [comment]
@vania-pooh  - Are we still looking into this thread?

**Comment by vania-pooh** [comment]
@maggosourabh not very actively.
