### ISSUE TITLE
selenoid vnc

### ISSUE THREAD

**Issue by Kinzabl** [aerokube/selenoid#1335]
Hello,
I want to know if using vnc with selenoid is secure. Does it use an encryption protocol?

**Comment by vania-pooh** [comment]
@Kinzabl it's using websockets over http or https depending on whether ui is running behind http or https.

**Comment by Kinzabl** [comment]
Ok. Thank you. I have another question does the test application use websocket too to communicate with selenoid? and the selenium commands are sent from the test app to the browser session created on the browser container or should pass by selenoid hub?

**Comment by Kinzabl** [comment]
and which protocol use selenoid to communicate with the client and the browser container?

**Comment by vania-pooh** [comment]
@Kinzabl Selenium W3C protocol is HTTP-based, so HTTP. Selenoid itself does not support TLS, because we consider this feature out of Selenoid scope. You can easily deliver TLS (HTTPS) connectivity to Selenoid using a well-known reverse-proxy like Nginx. Selenoid sends commands to browser containers using HTTP but these requests are being sent using Docker network and never quit VM or server where Selenoid runs (can be considered as requests to localhost).
