### ISSUE TITLE
Add ability to specify number of video recordings stored

### ISSUE THREAD

**Issue by rab2215** [aerokube/selenoid#309]
Selenoid should have an option to configure the max number of videos stored and once this limit is reached, the oldest videos would automatically roll off.  Without this HDD space will inevitably fill up, requiring the user to either manually delete files or create script to do this periodically.

**Comment by vania-pooh** [comment]
@rab2215 no, we will not implement it because it complicates the product. Currently in [this](http://aerokube.com/selenoid/latest/#_deleting_video_files) documentation section we provide two ways of dealing with this video rotation issue. Either delete old files by cron script or delete them via delete API for passed test cases. This is the same stuff as implementing log rotation logic in application instead of using `logrotate` tool.

**Comment by rab2215** [comment]
It seems as if making the user figure out some delete cycle on their own makes it much more complicated than just including, IMO, a necessary feature.  Even with including the delete API endpoint to delete passed test cases, the HDD space still becomes an issue in the event of really a really large number of failed tests.  This is unfortunate, especially seeing as how other similar video recording tools (and the one I'm currently using) has this feature.

**Comment by vania-pooh** [comment]
@rab2215 btw, which one are you using?

**Comment by rab2215** [comment]
https://github.com/aimmac23/selenium-video-node
