### ISSUE TITLE
Add ability to control video recording by client

### ISSUE THREAD

**Issue by MikeShysh** [aerokube/selenoid#336]
Hi,

Currently, video is recorded per driver session (one video file - per driver session). However, there is cases when it's needed to control the video recording by client. 
Use case:
There are several tests by driver session:
1) and it's needed to record video only for some exact tests.
2) and it's needed to store a video file only for failed tests.

Proposed changes help to reduce server load by videorecording, reduce size of the stored videofiles, allows to use video in reporting purposes more reliably. Mentioned cases could be achieved if video recording is controlled by client. 

I've already had video recording implementation based on common selenium grid in docker containers. Client has custom test listener, which sends start/stop recording requests to the selenium server node with customer Servlet. 
Here is an example of testng listener:
```
    @Override
    public void onTestStart(ITestResult result) {
     ...
     videoClient.set(new RemoteVideoClient(nodeUrl));
     ...
     videoClient.get().videoStart(getFileName(testResult));
    }
    @Override
    public void onTestSuccess(ITestResult result) {
           videoClient.get().videoStop(getFileName(result), true);  << 2nd parameter is a test result in order to remove video file for successful test
    }
    @Override
    public void onTestFailure(ITestResult result) {
            videoClient.get().videoStop(getFileName(result), false);  
    }
```
Here is an example of Servlet
https://github.com/MikeShysh/selenium-server-video/blob/master/src/main/java/com/portaone/videonode/core/VideoServlet.java

It would be great to implement some controls (API) for video recording. Could you please consider whether it's possible to do it in selenoid? I would like to help in implementation, but I need mentoring=)

**Comment by vania-pooh** [comment]
We are currently considering another approach which could help to solve the same issues. Will return to issue when finished.

**Comment by presidenten** [comment]
Any update on this?

**Comment by vania-pooh** [comment]
@presidenten right now our approach is to save one video per session. We also allow to remove useless video files via API or directly on the file system. Stopping and restarting video recording means creating several video files per session. How would you name them? How would you deal with such files?

**Comment by MikeShysh** [comment]
@vania-pooh to my mind, the aim of this task is to implement client side. It means that client is in charge of naming such files. 
Selenoid needs to provide an api, where user can specify driver sessionID (as a key to find the needed running container), start/stop videorecording flags and video file name parameter.

**Comment by presidenten** [comment]
Maybe a rest-api?
```
POST /video/start-recording
  msg: { 
    filename,
    resolution,
    fps,
   }  

POST /video/stop-recording 
  msg: { 
     filename, 
     deleteOrKeep
   }
```

**Comment by aandryashin** [comment]
It is possible to implement such functionality as separate service for
example as part of video-recorder, but not in selenoid. If you wish you can
implement such service pack to your own video-recorder container and use it
with selenoid.

2018-05-24 14:50 GMT+03:00 Johan Hernefeldt <notifications@github.com>:

**Comment by presidenten** [comment]
@aandryashin Sounds like a good idea to put in the video-recorder. 
But then we would need to get hold of the ip of the browsers recorder docker container in the browser container somehow. Would it be possible for you guys to set it as a environment variable?

Also, Im a docker n00b, but would still like to try to give it a go with the video-recorder api. 
Do you guys have like a gitter dev channel where I could ask questions if I get stuck?
Like how to make selenoid launch my version of video-recorder for example.

**Comment by vania-pooh** [comment]
@presidenten we have a Telegram channel only https://t.me/aerokube

**Comment by presidenten** [comment]
Becuase messages zoom by so fast in the telegram channel, Ill add my findings here as well

I managed to control the video recording by working with a custom video recorder (almost same as official, but does not start ffmpeg on startup). Here is an example repo containing a node library that can be used by webdriver io for example to record each separate failing test case. I guess the functionality could be exposed as a rest-api as well. But I took the easy way now, since I use webdriver.io which is also in node.

https://github.com/presidenten/selenoid-video-api

Check out the ”Run the demo” and ”Under the hood” sections in the readme here for more info:
Also have a look at `lib/video.js` to see docker integration.

In the demo I use `beforeTest`/`afterTest` hooks to start/stop video recordings that are named after the tests and only store videos from failed tests.

So what are your thoughts? Is this something we could add to selenoid somehow?

Custom recorder is here:
https://hub.docker.com/r/presidenten/selenoid-manual-video-recorder/
Repo here:
https://github.com/presidenten/selenoid-manual-video-recorder-image

Caveats with the demo:
- Only tested on mac
- I could not find a good way to find the browser ip from within the test. Anyone got a better solution than mine?
- I could not find a good way to know when vnc is up and running. So right now I need to pause for 2s, or the first firefox videos become black. A nice solution here would be nice as well...

Anyways, please check it out! :)

**Comment by vania-pooh** [comment]
Closing this one. Thank you, @presidenten for contribution.
