### ISSUE TITLE
Swarm support

### ISSUE THREAD

**Issue by remy-tiitre** [aerokube/selenoid#368]
Have you thought about adding Docker Swarm support so that browser container could run on other nodes as well.

**Comment by vania-pooh** [comment]
@remy-tiitre we personally do not plan to add it ourselves - we are not using Swarm and think that Kubernetes will be the winner. However we are open for PRs adding this support. To do this you have to implement [Starter](https://github.com/aerokube/selenoid/blob/master/service/service.go#L49) interface.

**Comment by SgtPooki** [comment]
what is the difference between selenium-hub + selenium-node in docker, selenoid, docker swarm with selenium-hub and selenium-node, and kubernetes? I'm not really sure I understand the benefits of selenoid.. 

Is this just a lib for config-less/hassle-less selenium?

**Comment by vania-pooh** [comment]
@SgtPooki Selenoid is a Golang implementation of Selenium protocol using Docker to launch browser sessions (so it a replacement of Java-based Selenium server). Currently it supports working with Docker directly (no support for Swarm or Kubernetes).

**Comment by SgtPooki** [comment]
Thanks @vania-pooh! That’s a really helpful and concise explanation.

**Comment by Wolfium** [comment]
The limitation comes from the Docker client API SDK which does not have swam(stacks) calls implemented already, currently they are all implemented at the docker cli command line utilities.
So, in the meantime, it has to be launched as plain shell commands.
There is an readmap item to move stack api to server side which would bring better context implementation options because at this moment it is implemented all docker cli command line.

Regards

**Comment by ismailazerty** [comment]
It would be great if selenoid can use docker swarm to launch browsers, it would become by far the most complete tool available. please find a way to do that.

**Comment by sergeygardner** [comment]
> It would be great if selenoid can use docker swarm to launch browsers, it would become by far the most complete tool available. please find a way to do that.

it's possible. I have already launched selenoid in swarm.
You should create an external network for a selenoid stack and link it with your stack application. You could resolve some aliases for the selenoid network at the stack e.g. selenoid.local. And in your test cases put selenoid.local as the host.

Also you could add to the selenoid stack some prepulled browser images e.g. chrome:latest, firefox etc.

It's not necessary to add additionalNetwork in a capabilities configuration because linked network between stack services have visibility each other.
