### ISSUE TITLE
Option to always try to pull image before creating

### ISSUE THREAD

**Issue by monkpit** [aerokube/selenoid#437]
I am trying to deploy selenoid in our environment where docker cache is unpredictable (might have been emptied / cleaned up / never existed in the first place). Would it be possible to add a flag like `-e ALWAYS_PULL_IMAGES=1` or similar, so that selenoid will attempt to `docker pull` an image before trying to create it?

Otherwise I see this in the logs at random: `WebDriverError: create container: Error: No such image: selenoid/vnc:chrome_65.0`

And it's not an option to pull the image into the cache "ahead of time" because our policy is that the docker image cache can be removed at any time (for the purposes of saving disk space).

**Comment by vania-pooh** [comment]
@monkpit this question about auto-pull feature is asked all the time Selenoid exists.  We do not implement this feature intentionally because pulling images during test run can influence stability. What you could do is to set a cron job automatically syncing Docker images with existing browsers.json ([docs](https://aerokube.com/selenoid/latest/#_syncing_browser_images_from_existing_file)). However I would just do not clean Selenoid images (add an exclusion) as all browser images take several gigabytes only and hard disks are cheap today.

**Comment by monkpit** [comment]
I will close the issue if this will not be implemented, however I still think it is a necessary feature.

Consider a situation where you have 10 docker hosts that could possibly run Selenoid, depending on the demand for tests. 9 of the machines already have pulled and cached the Selenoid images, but the 10th one has newly joined the pool of hosts.

When the host is provisioned, it doesn't have any specific knowledge of Selenoid or knowledge of which images Selenoid will use, so it doesn't know to pull / cache the images ahead of time.

Now, demand for tests is high and some tests try to run on host 10 - these tests will fail. The only way to fix this is to create some kind of script to be run during provisioning that is specific to Selenoid - which is something I want to avoid.

**Comment by vania-pooh** [comment]
@monkpit such stuff is resolved with Ggr quota files. You add new Selenoid hosts to Ggr quota file only when it is fully provisioned.

**Comment by monkpit** [comment]
Ok - thanks for the responses! Cheers :beers:
