### ISSUE TITLE
Ability to proxy Chrome Debug Protocol

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/selenoid#607]
Sometimes more powerful Chrome features are needed.

**Comment by vania-pooh** [comment]
Should use port value passed via ChromeOptions or add own value.
```
POST 	 "/wd/hub/session"
{
	"desiredCapabilities": {
		"browserName": "chrome",
		"enableVNC": true,
		"chromeOptions": {
			"args": ["--remote-debugging-port=35553"]
		}
	}
}
```

**Comment by BorisOsipov** [comment]
@vania-pooh 
Awesome 👍. Am I rigth that is available now for the latest chrome image? Or we need to wait sometime till image will update

**Comment by vania-pooh** [comment]
@BorisOsipov works with `vania-pooh/chrome:71.0-devtools`.

**Comment by admizh** [comment]
please add any examples here, Can help how to get 'HAR' files with preserved logs?

**Comment by vania-pooh** [comment]
@admizh still investigating why sometimes this does not work.

**Comment by uudens** [comment]
Hi, maybe you could advise or provide a working example?

I am unable to run chrome devtools protocol commands with selenoid.
I'm using the image `vaniapooh/chrome:71.0-devtools`

This is what I'm trying:
1. run a test with selenoid and get a session id
2. use some basic tool ([websocat](https://github.com/vi/websocat)) to connect to ws
3. try to run some CDP commands
```
$ websocat ws://127.0.0.1:4444/devtools/612166466a30e961adcb27638941456f
{"id":1,"method":"Browser.getVersion"}
{"id":1,"result":{"protocolVersion":"1.3","product":"Chrome/71.0.3578.98","revision":"@15234034d19b85dcd9a03b164ae89d04145d8368","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36","jsVersion":"7.1.302.31"}}
{"id":2,"method":"Performance.getMetrics"}
{"error":{"code":-32601,"message":"'Performance.getMetrics' wasn't found"},"id":2}
```
For some reason Performance.getMetrics is not working, but it should be available [since Chrome 64](https://chromedevtools.github.io/devtools-protocol/). Other common commands are also not found.

This is my capabilities config:
```
    capabilities: [{
        browserName: "chrome",
        enableVNC: true,
        chromeOptions: {
            args: ["--remote-debugging-port=9222"],
        },
    }],
```
Could you please help or provide a working example?
Thank you in advance!

**Comment by BorisOsipov** [comment]
hi @uudens 

there is an issue with proxing cdp port. subscribe to https://github.com/aerokube/selenoid/issues/700 to stay tuned.

**Comment by jayden-xie** [comment]
> @admizh still investigating why sometimes this does not work.

Does it still exists? Get HAR from devtools.

**Comment by vania-pooh** [comment]
@jayden-xie yes, it should work.

**Comment by jayden-xie** [comment]
@vania-pooh 
I tried vaniapooh/chrome:75.0-devtools, but all those API return empty result with 200 status.
<ws or http>://selenoid.example.com:4444/devtools/<session-id>/<method>

Do you have plan to build a template on Azure for Moon? And will you add network recording in Moon?

**Comment by vania-pooh** [comment]
@jayden-xie just try any recent Chrome image, e.g. `selenoid/chrome:79.0`
