### ISSUE TITLE
Any way to limit node containers memory?

### ISSUE THREAD

**Issue by Exoticalgi** [aerokube/selenoid#98]
Is there any possibility to limit node containers memory?
I can use -m with docker when launching hub, but what about nodes?

Thank you.

**Comment by vania-pooh** [comment]
Related to https://github.com/aerokube/selenoid/issues/63.

**Comment by vania-pooh** [comment]
@Exoticalgi currently there's no support for this. But let us discuss a bit how we could better implement this feature. We agree that it's important.

**Comment by Exoticalgi** [comment]
Maybe by setting memory limit for particular image in browsers.json and read it when launching (equivalent to docker -m parameter).

**Comment by vania-pooh** [comment]
@Exoticalgi yes, we consider adding a new field to `browsers.json` as one of the main solutions. Will implement somehow during next days.

**Comment by Exoticalgi** [comment]
I will be happy to test this feature.

**Comment by vania-pooh** [comment]
Fixed in https://github.com/aerokube/selenoid/commit/7901f15f0956bafdeaba194fc4a41e1043679c44.
@Exoticalgi finally we decided to implement this as a global flag `-mem` and for cpu `-cpu` applied to each container. E.g.:
```
$ selenoid -mem 128m
```
Memory is specified in Docker format: https://docs.docker.com/engine/admin/resource_constraints/

Same stuff with CPUs:
```
$ selenoid -cpu 1.5
```
Specified as float value, e.g. 0.2 means 1/5 of CPU. Docs will be updated soon. Please confirm whether this works for you.
